2023-05-19 15:49:41,565 ERROR 77137 [-/127.0.0.1/-/0ms GET /] nodejs.ER_NOT_SUPPORTED_AUTH_MODEError: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Sequence._packetToError (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Protocol._enqueue (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Pool.js:48:16)
    at node:internal/util:367:7
    at new Promise (<anonymous>)
    at Pool.getConnection (node:internal/util:353:12)
    at Pool.query (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Pool.js:202:8)
    at node:internal/util:367:7
    at new Promise (<anonymous>)
    sql: select now() as currentTime;
code: "ER_NOT_SUPPORTED_AUTH_MODE"
errno: 1251
sqlMessage: "Client does not support authentication protocol requested by server; consider upgrading MySQL client"
sqlState: "08004"
fatal: true
name: "ER_NOT_SUPPORTED_AUTH_MODEError"
pid: 77137
hostname: Stone-xdeMacBook-Pro.local

2023-05-19 15:51:23,775 ERROR 77292 [-/127.0.0.1/-/0ms GET /] nodejs.ER_NOT_SUPPORTED_AUTH_MODEError: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Sequence._packetToError (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Protocol._enqueue (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Pool.js:48:16)
    at node:internal/util:367:7
    at new Promise (<anonymous>)
    at Pool.getConnection (node:internal/util:353:12)
    at Pool.query (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Pool.js:202:8)
    at node:internal/util:367:7
    at new Promise (<anonymous>)
    sql: select now() as currentTime;
code: "ER_NOT_SUPPORTED_AUTH_MODE"
errno: 1251
sqlMessage: "Client does not support authentication protocol requested by server; consider upgrading MySQL client"
sqlState: "08004"
fatal: true
name: "ER_NOT_SUPPORTED_AUTH_MODEError"
pid: 77292
hostname: Stone-xdeMacBook-Pro.local

2023-05-19 15:51:43,153 ERROR 77457 [-/127.0.0.1/-/0ms GET /] nodejs.ER_NOT_SUPPORTED_AUTH_MODEError: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Sequence._packetToError (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Protocol._enqueue (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Pool.js:48:16)
    at node:internal/util:367:7
    at new Promise (<anonymous>)
    at Pool.getConnection (node:internal/util:353:12)
    at Pool.query (/Users/stone_x/Desktop/Personal Ledger/egg-example/node_modules/mysql/lib/Pool.js:202:8)
    at node:internal/util:367:7
    at new Promise (<anonymous>)
    sql: select now() as currentTime;
code: "ER_NOT_SUPPORTED_AUTH_MODE"
errno: 1251
sqlMessage: "Client does not support authentication protocol requested by server; consider upgrading MySQL client"
sqlState: "08004"
fatal: true
name: "ER_NOT_SUPPORTED_AUTH_MODEError"
pid: 77457
hostname: Stone-xdeMacBook-Pro.local

2023-05-19 19:45:31,131 ERROR 82810 nodejs.ClusterClientNoResponseError: client no response in 606703ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 82810
hostname: Stone-xdeMacBook-Pro.local

2023-05-19 20:02:24,551 ERROR 82810 nodejs.ClusterClientNoResponseError: client no response in 973406ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 82810
hostname: Stone-xdeMacBook-Pro.local

2023-05-19 20:18:30,896 ERROR 82810 nodejs.ClusterClientNoResponseError: client no response in 926347ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 82810
hostname: Stone-xdeMacBook-Pro.local

2023-05-20 16:41:56,669 ERROR 27632 [-/127.0.0.1/-/21ms GET /api/user/test] nodejs.JsonWebTokenError: jwt must be provided
    at module.exports [as verify] (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/jsonwebtoken/verify.js:53:17)
    at <computed>.verify (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/egg-jwt/app/extend/application.js:42:20)
    at UserController.test (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/app/controller/user.js:109:34)
    at Object.callFn (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/koa-compose/index.js:44:32)
    at next (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/koa-compose/index.js:45:18)
    at /Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/@eggjs/router/lib/router.js:186:18
name: "JsonWebTokenError"
message: "jwt must be provided"
pid: 27632
hostname: Stone-xdeMacBook-Pro.local

2023-05-20 16:45:37,141 ERROR 28192 [-/127.0.0.1/-/4ms GET /api/user/test] nodejs.JsonWebTokenError: jwt must be provided
    at module.exports [as verify] (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/jsonwebtoken/verify.js:53:17)
    at <computed>.verify (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/egg-jwt/app/extend/application.js:42:20)
    at UserController.test (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/app/controller/user.js:109:34)
    at Object.callFn (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/koa-compose/index.js:44:32)
    at next (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/koa-compose/index.js:45:18)
    at /Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/@eggjs/router/lib/router.js:186:18
name: "JsonWebTokenError"
message: "jwt must be provided"
pid: 28192
hostname: Stone-xdeMacBook-Pro.local

2023-05-20 16:45:57,937 ERROR 28335 [-/127.0.0.1/-/22ms GET /api/user/test] nodejs.JsonWebTokenError: jwt must be provided
    at module.exports [as verify] (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/jsonwebtoken/verify.js:53:17)
    at <computed>.verify (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/egg-jwt/app/extend/application.js:42:20)
    at UserController.test (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/app/controller/user.js:109:34)
    at Object.callFn (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/koa-compose/index.js:44:32)
    at next (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/koa-compose/index.js:45:18)
    at /Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/@eggjs/router/lib/router.js:186:18
name: "JsonWebTokenError"
message: "jwt must be provided"
pid: 28335
hostname: Stone-xdeMacBook-Pro.local

2023-05-20 16:45:59,786 ERROR 28335 [-/127.0.0.1/-/2ms GET /api/user/test] nodejs.JsonWebTokenError: jwt must be provided
    at module.exports [as verify] (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/jsonwebtoken/verify.js:53:17)
    at <computed>.verify (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/egg-jwt/app/extend/application.js:42:20)
    at UserController.test (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/app/controller/user.js:109:34)
    at Object.callFn (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/koa-compose/index.js:44:32)
    at next (/Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/koa-compose/index.js:45:18)
    at /Users/stone_x/Desktop/Personal Ledger/Ciara-server/node_modules/@eggjs/router/lib/router.js:186:18
name: "JsonWebTokenError"
message: "jwt must be provided"
pid: 28335
hostname: Stone-xdeMacBook-Pro.local

2023-05-21 19:14:53,553 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 606500ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-21 19:31:31,639 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 918026ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-21 19:49:43,953 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 972273ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-21 20:06:45,098 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 941137ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-21 20:23:17,153 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 952059ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-21 20:39:40,274 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 803013ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-21 20:56:40,155 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 606935ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-21 21:12:32,533 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 912371ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-21 21:56:52,966 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 958132ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-21 22:14:00,493 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 987517ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-21 22:23:14,755 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 514249ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-21 22:36:26,267 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 111473ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-21 22:40:22,547 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 196204ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

